language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm ci
  - npm test
  - npm run build

env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build
  skip_cleanup: true
  on:
    branch: master
